### ISSUE TITLE
Separate connector definitions

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/RADAR-Schemas#112]
In the RADAR-Schemas hierarchy, I have the feeling that `connector` should be a separate category from `passive`, `active`, `monitor` and `stream`. For example, we should not register the `connector` schemas during initialisation, because the Kafka Connector code will do that instead. If we try to do it, there will be an incompatibility between the schema that the connector provides and the one that we provide, because the Kafka Connector adds some connect-specific properties to the schema. Also, the connector does not have an app-provider, but it could have the name of the source connector.

Alternatively, we could add a flag in the specifications that says something like `register_schema: false`.

@yatharthranjan @nivemaham what do you think?

**Comment by yatharthranjan** [comment]
I think it would be worth to keep the schemas in the repo but flag them if to register or not. Right now are there any schemas in the repo for connectors ?

**Comment by blootsvoets** [comment]
They would be added for the Fitbit connector. I don't mean not adding them, just perhaps to add a new source category `connector`, since we probably will get more of those eventually.

**Comment by yatharthranjan** [comment]
Okay got it. Yes that makes a lot of sense. So only the topics will be created in this case ?

**Comment by blootsvoets** [comment]
Exactly

**Comment by nivemaham** [comment]
Sounds good to me

**Comment by yatharthranjan** [comment]
closed by #119
