### ISSUE TITLE
Rest Proxy does not support optional schemas anymore

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-Schemas#153]
Due to an update to avro, the rest proxy does not support omitting optional fields from the payload anymore. 
More info here https://github.com/confluentinc/kafka-rest/issues/173 and https://github.com/confluentinc/kafka-rest/issues/427 
I have tested this (with `timeNotification` being optional) on confluent platform 4.1.0 and the following does not work --

```
...
"value"":{"string":"3"},"startTime":1537462650.709,"endTime":1537462652.472}],"time":1537462633.167,"timeCompleted":1537462652.472},
...
```
giving the error -- `{"error_code":42203,"message":"Conversion of JSON to Avro failed: Failed to convert JSON to Avro: Expected start-union. Got END_OBJECT"}`

but adding null for the optional field works -- 
```
"value":{"string":"3"},"startTime":1537462650.709,"endTime":1537462652.472}],"time":1537462633.167,"timeCompleted":1537462652.472,"timeNotification":null},
```

This causes some compatibility and evolution issues. Should we fork the rest-proxy repo and create a manual fix for this ??

@blootsvoets @afolarin

**Comment by blootsvoets** [comment]
Perhaps we should... or let the gateway perform the conversion ahead of time?... The following [snippet on the Avro mailing list](https://issues.apache.org/jira/plugins/servlet/mobile#issue/AVRO-1915) could help:
```java
MessageEncoder<Record> v1Encoder = new BinaryMessageEncoder<Record>(GenericData.get(), SCHEMA_V1);
BinaryMessageDecoder<Record> v2Decoder = new BinaryMessageDecoder<Record>(GenericData.get(), SCHEMA_V2);
// add the older version to the decoder so it can handle both v1 and v2 messages (you can do this with as many as you need)
v2Decoder.addSchema(SCHEMA_V1);

// encode the v1 record (on the producer side)
ByteBuffer v1Buffer = v1Encoder.encode(v1record);

// decode the v1 record to the expected v2 schema (on the consumer side)
Record v2record = v2Decoder.decode(v1Buffer);
```

**Comment by yatharthranjan** [comment]
This can also be handled on the client side

**Comment by yatharthranjan** [comment]
This was handled in the Client but as a failsafe perhaps the Gateway should also perform this check and conversion. Will create an issue in gateway.
