### ISSUE TITLE
Add timezone to commons 'application' schemas

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/RADAR-Schemas#22]
Right now, we send time values in seconds in UTC, however, for a proper day analysis, we probably also need to send timezone somewhere. This doesn't necessarily have to be sent in each message, but it should at least be sent by the application. The most direct would be to send the [UTC offset](https://en.wikipedia.org/wiki/UTC_offset), where an offset of one hour compared to UTC would be `"+01:00"`, `"+0100"`, or simply `"+01"`. Using a time zone string would reveal more about someones location.

**Comment by yatharthranjan** [comment]
Close as fixed
