### ISSUE TITLE
Schema compatibility is set to FULL. 

### ISSUE THREAD

**Issue by nivemaham** [RADAR-base/RADAR-Schemas#230]
We used to set schema compatibility to NONE. Kafka-init from 0.5.10.1 sets compatibility to FULL, which disallows updates of schemas that do not comply with FULL evolution. (i.e adding new fields)

**Comment by blootsvoets** [comment]
IIRC, the behaviour of setting the compatibility to `FULL` has not changed. However, it is only applied if the `--force` flag is given to `radar-schemas-tools register` in kafka-init (as it is, in https://github.com/RADAR-base/RADAR-Schemas/blob/07c13521564399bed5f5252373b713870d304c05/docker/topic_init.sh#L39). The force flag could be removed, or it the compatibility could be changed at the end of the script using a curl command to the schema registry.
