### ISSUE TITLE
Migrate the gradle-avro-plugin

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-Schemas#260]
Migrate the Gradle avro plugin to https://github.com/davidmc24/gradle-avro-plugin as the current one is now unsupported.

New plugin IDs: `com.github.davidmc24.gradle.plugin.avro` and `com.github.davidmc24.gradle.plugin.avro-base`
New package for tasks: `com.github.davidmc24.gradle.plugin.avro`

**Comment by blootsvoets** [comment]
Fixed in #246
