### ISSUE TITLE
Retry sleep/backoff not working

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-Schemas#281]
moved from #272 

> The maximum no. of retries on refreshing topics has been set to 10 and that's oh. However, the retry back-off seems not working/existing or the timeout is too short so they all happed within one sec:
https://github.com/RADAR-base/RADAR-Docker/runs/3203037035?check_suite_focus=true#step:6:185

> More details in here:
https://github.com/RADAR-base/RADAR-Schemas/blob/master/java-sdk/radar-schemas-registration/src/main/java/org/radarbase/schema/registration/KafkaTopics.java#L193-L230

**Comment by blootsvoets** [comment]
Closed by #282.
