### ISSUE TITLE
Initial End-to-End Feasibility

### ISSUE THREAD

**Issue by afolarin** [RADAR-base/RADAR-Schemas#3]
We want as a starting point to test an end-to-end ingestion pipeline. This will include i) a single passive sensor stream (either phone or wearable device) and ii) questionnaire

The first suggestions are we use for the passive sensor stream either:
- Heart Rate sensor
- Accelerometer

This and the initial questionnaire schema are therefore a priority.

**Comment by blootsvoets** [comment]
For the Empatica E4 device, we needed something right away, especially the Avro schemas. See the [backend schema directory](https://github.com/RADAR-CNS/RADAR-Backend/tree/master/src/main/resources/org/radarcns/collect/schema) for preliminary schemas for at least the Empatica E4. They might be generalised to the other devices, so far the JSON schemas that we saw are very similar.

Additional streams are at least:
* blood volume pulse ([PPG](https://en.wikipedia.org/wiki/Photoplethysmogram))
* battery level
* device status
* electrodermal activity
* body temperature
* inter-beat-interval (extracted from the PPG, inverse to heart rate, with heart rate = 60 / inter-beat-interval, perhaps with a sliding average)

**Comment by yatharthranjan** [comment]
i believe this is ok to close?

**Comment by blootsvoets** [comment]
Indeed this is part of a radar-commons-testing package (mockproducer)
